apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2024-11-13T06:00:13Z","generation":1,"labels":{"app":"lorawan-simulator"},"name":"lorawan-simulator-deployment","namespace":"default","resourceVersion":"10376624","uid":"28131b09-b958-4b08-bb05-82cb90a3cab4"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"lorawan-simulator"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"lorawan-simulator"}},"spec":{"containers":[{"image":"matthewxxxx/lorawan-simulator:latest","imagePullPolicy":"Always","name":"lorawan-simulator","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2024-11-13T06:00:13Z","lastUpdateTime":"2024-11-13T06:00:18Z","message":"ReplicaSet \"lorawan-simulator-deployment-7f7f646ff5\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2024-11-20T23:10:15Z","lastUpdateTime":"2024-11-20T23:10:15Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2024-11-13T06:00:13Z"
  generation: 2
  labels:
    app: lorawan-simulator
  name: lorawan-simulator-deployment
  namespace: default
  resourceVersion: "10399276"
  uid: 28131b09-b958-4b08-bb05-82cb90a3cab4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: lorawan-simulator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lorawan-simulator
    spec:
      containers:
      - image: matthewxxxx/lorawan-simulator:dev-latest
        imagePullPolicy: Always
        name: lorawan-simulator
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-11-13T06:00:13Z"
    lastUpdateTime: "2024-11-13T06:00:18Z"
    message: ReplicaSet "lorawan-simulator-deployment-7f7f646ff5" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-11-20T23:10:15Z"
    lastUpdateTime: "2024-11-20T23:10:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
